### ISSUE TITLE
FYI: xen upstream minimum vgpu patches

### ISSUE THREAD

**Issue by mcerveny** [kharbranth/vGPU-unlock-Kepler-xcp-ng#1]
I tested my upstream xen 4.13.3 (not XS) with updated patches from citrix (attached) for my modified vgpud.
```
# rpm -i xen-4.13.3-1.fc32.src.rpm
# patch -p0 < xen_spec.patch
# cd rpmbuild/SPECS/
# rpmbuild -bb xen.spec --without ocaml --without docs --without stubdom --without qemutrad
# cd ../RPMS/x86_64/ 
## install rpms
```
[xen-4.13.3-1.fc32_vgpu_minimum_20210503.tar.gz](https://github.com/kharbranth/vGPU-unlock-Kepler-xcp-ng/files/6412366/xen-4.13.3-1.fc32_vgpu_minimum_20210503.tar.gz)

**Comment by kharbranth** [comment]
Hello, thanks for responding. 

I realized that XS (or xcp-ng) does not actually have all the patches that your minimum patchset has (for example, `add-m2b-support.patch` is completely missing in XS xen package). I am going to rebuild on Fedora (or maybe openSUSE) with your patches next week and try again.

Thank you for the hints!

**Comment by mcerveny** [comment]
M2B was eliminated https://github.com/xenserver/xen.pg/commit/405a736bc2b3c3267ce5b014f809fb5f5da78ede
I build my xen as "upstream xen" and "qemu-xen" (no patches need). qemu-tradional is eliminated. This brings need to additional rework of citrix "vgpud".

So summary (updated discord HINT):
1. apply patches for PV_IOMMU (xen upstream ignores it, so use [citrix xenserver](https://github.com/xenserver/xen.pg/)) - DONE  
2. create "vgpud" ioreq_server (vgpu paravirtualization daemon runs parallel to qemu) (opensource part of vgpu-7.3.0-1.src.rpm in XenServer-7.4.0-update-sources.iso, closed part is in NVIDIA xen packages - libnvidia-vgpu.so) - need many reworks to update from qemu-dm to qemu-xen like VGA BIOS, update UEFI BIOS (TianoCore), update VGA emulation code... VGA emulation is embedded in "vgpud" do not attach other VGA (you already checked outcome) but reserve RAM (xl.cfg hints - `vga="none", videoram=16, mmio_hole=1024`). You should try to boot to preinstalled windows without VGA BIOS and with enabled guest based RDP. Preinstall windows with normal VGA and qemu based VNC server (xl.cfg - `vga="stdvga"`) and do not forget to backup disk image or use snapshots (like ZFS).
3. update "vgpud" to interact with some display streaming (like vnc,spice ... or other) or use guest based RDP (“Use the hardware default graphics adapter for all Remote Desktop Services sessions”). I developed my [own mjpeg/h264 streaming](https://forums.developer.nvidia.com/t/vdi-click-to-photon-with-raspberry-pi/162237) over UDP .
4. run both "qemu" and "vgpud" with xen VM startup... and done in XEN the next challenge is management extension. Simply modidy "xl.cfg" - `device_model_override=some.sh, device_model_args=some_params`). I developed my own extension based on libxl. I do not use xe,xm,virsh...

**Comment by kharbranth** [comment]
Thank you for the updated summary. For my own reference, these things were "DONE"/"NOT DONE" according to myself:

- (1) PV-IOMMU patches: **DONE** (will be re-done with Fedora/your minimal working patchset)
- (2) compilation of Citrix vGPU ioreq_server: **DONE**
- (2) Citrix vGPU ioreq_server patches to work with unpatched qemu-xen: **NOT DONE**
- (2) Install/snapshot Windows (7) with only default VGA adapter: **DONE**
- (4) Run QEMU and Citrix vGPU daemon at the same time when starting VMs: **DONE**
- (2) Remove `stdvga` adapter and use vGPU adapter only with host RDP: **DONE** (there was still a Code 12 error, this may have to do with the missing params in the next bullet point)
- (2) `xl.cfg` params for `mmio_hole` and `videoram`: **NOT DONE**
- (3) Management extension/UDP-based vGPU streaming: **NOT DONE; WILL BE DONE AFTER BASIC FUNCTIONALITY IS ESTABLISHED**

I only have one note. You mentioned that you patched Citrix vGPU daemon to work with an unpatched `qemu-xen`. However, it looks like [this](https://github.com/xcp-ng-rpms/qemu/blob/master/SOURCES/0001-CP-17697-Initial-port-of-NVIDIA-VGPU-support-from-QEMU-trad.patch) QEMU patch is what they are using in upstream XenServer today (I believe that upstream XenServer no longer uses `qemu-dm`/qemu-traditional but rather is using the `qemu-xen` upstream QEMU). I may not be understanding this properly, but this code is very similar to the old code from when XS used `qemu-dm`. I am thinking that it is possible to patch QEMU instead of Citrix's vGPU implementation, but I may be wrong.

I will probably know more once I have time to test things again.

**Comment by mcerveny** [comment]
Progress is slow, let's accelerate. 
I simplified and **verified** startup solution (without  console access, VBIOS...). RTX2070S with T4-1Q profile is used and magic script is running (so not Kepler). No patches to qemu-xen.
- apply `vgpu-7.3.0-remove_mig.patch` that removes dependency to citrix EMP (live host migration) && compile
- study && modify `win1_manual_vgpu.cfg`
- study && modify `qemu_and_vgpu.sh` referred from win1_manual_vgpu.cfg
- start `xl create win1_manual_vgpu.cfg`
- check logs `ls -ltr /var/log/xen/*win1_manual.log`
- check syslog (vgpu is logging to syslog) `grep vgpu- /var/log/messages`
- RDP or VNC (better but need install VNC server to windows guest) to windows

[vgpu_xen_startup_20210504.tar.gz](https://github.com/kharbranth/vGPU-unlock-Kepler-xcp-ng/files/6421032/vgpu_xen_startup_20210504.tar.gz)

**Comment by mcerveny** [comment]
> I only have one note. You mentioned that you patched Citrix vGPU daemon to work with an unpatched `qemu-xen`. However, it looks like [this](https://github.com/xcp-ng-rpms/qemu/blob/master/SOURCES/0001-CP-17697-Initial-port-of-NVIDIA-VGPU-support-from-QEMU-trad.patch) QEMU patch is what they are using in upstream XenServer today (I believe that upstream XenServer no longer uses `qemu-dm`/qemu-traditional but rather is using the `qemu-xen` upstream QEMU).

vgpu **implements VGA** code (see device.c, Copyright (c) 2003 Fabrice Bellard). It renders VGA to **pixelbuffer** (see demu_state.vram and surface_state.shared). It is used if NVIDIA guest driver is not loaded (see demu_state.console_active). When NVIDIA guest driver loads, the same **pixelbuffer** is used for **framecopy engine** in guest driver (no need to load aditional software in guest). Framecopy FPS is set by parameter "intervaltime=33333" (equals to 30FPS, standard is 5FPS). Beware framecopy engine does not copy HW rendered mouse :-) So, this **pixelbuffer** can be used as source actual graphics (or text rendered to graphics) console output. Patch to qemu-xen (or qemu-dm) allows access this pixelbuffer to qemu and qemu can encode this buffer to qemu based server VNC. I used this pixelbuffer directly in vgpu to encode and stream (mjpeg (on CPU) or nvenc (in different guest domain, because in host domain [CUDA is inaccessible](https://forums.developer.nvidia.com/t/cuda-in-dom0/161937) and therefore NVENC is inaccessible). This solution is better then VMWARE (and probably KVM) VGA console independent emulation (see [CAUTION](https://docs.nvidia.com/grid/12.0/grid-software-quick-start-guide/index.html#configure-vmware-vsphere-vm-with-vgpu)).

**Comment by kharbranth** [comment]
I retested on Fedora 32 with the instructions you gave in the comment with `vgpu_xen_startup_20210504.tar.gz`. 

First, I installed Windows 7 as domU with the standard VGA (`vga="stdvga",vnclisten="0.0.0.0:1",vnc=1`) drivers and backed up the image in case of failure. I commented out the `device_model_override`/`device_model_version` lines for this as it seems that the `qemu_and_vgpu.sh` is for starting the VM with the vGPU in it. I also commented out `device_model_args`. Then, I enabled RDP.

I removed the QEMU VNC configuration and removed the VGA adapter, re-added the `device_model_args`, and the `device_model_version` and `device_model_override`. Then, I started the domain again, went into RDP, and installed the drivers. The drivers install fine and there is no Code 28 error from before. However, the problem arises when Windows reboots—instead of rebooting into Windows as normal, I think the driver is causing the system to BSoD. This error is very similar to some other testing I had done on a Windows 10 domU when I was testing on xcp-ng (XenServer). The driver would install properly, but a reboot would cause a blue screen of death immediately after Citrix vgpud detects the guest driver information. 

I do not have logs for the BSOD from this Windows 7 attempt, but since Windows 10 automatically loaded the Xen guest drivers (`xenbus` specifically I think), I was able to get the logs for the BSOD.

```
May  1 10:48:37 xcp-ng-gounbjgq qemu-dm-1[4564]: 4564@1619880517.441751:xen_platform_log xen platform: xen|BUGCHECK: SYSTEM_SERVICE_EXCEPTION: 00000000C0000005 FFFFF8033F619E32 FFFFF2801F5F43A0 0000000000000000
May  1 10:48:37 xcp-ng-gounbjgq qemu-dm-1[4564]: 4564@1619880517.441830:xen_platform_log xen platform: xen|BUGCHECK: EXCEPTION (FFFFF8033F619E32):
May  1 10:48:37 xcp-ng-gounbjgq qemu-dm-1[4564]: 4564@1619880517.441897:xen_platform_log xen platform: xen|BUGCHECK: - Code = 49C83C89
May  1 10:48:37 xcp-ng-gounbjgq qemu-dm-1[4564]: 4564@1619880517.441956:xen_platform_log xen platform: xen|BUGCHECK: - Flags = 04F0868B
May  1 10:48:37 xcp-ng-gounbjgq qemu-dm-1[4564]: 4564@1619880517.442057:xen_platform_log xen platform: xen|BUGCHECK: - Address = C86483000004F086
May  1 10:48:37 xcp-ng-gounbjgq qemu-dm-1[4564]: 4564@1619880517.442128:xen_platform_log xen platform: 
<truncated>
```

Considering that you tested a similar Xen + vgpu setup as well, I am assuming that it should work, but does not (I could test this on a Pascal GPU as well). 

I wonder if the problem here is that I did not patch something somewhere (I am trying to do this quickly), or if it is because my graphics card is a GK110 model, which is not what the GRID K(1|2) models are (those are GK104).

**Comment by mcerveny** [comment]
> * check logs `ls -ltr /var/log/xen/*win1_manual.log` 
> * check syslog (vgpu is logging to syslog) `grep vgpu- /var/log/messages`

This logs needed.
You can add more vgpud debugging parameters to - like 
Can you check K110 in host ? 

my K1 host BARs:
```
87:00.0 VGA compatible controller: NVIDIA Corporation GK107GL [GRID K1] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: NVIDIA Corporation Device 1012
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 199
	Region 0: Memory at f4000000 (32-bit, non-prefetchable) [size=16M]
	Region 1: Memory at 381fc8000000 (64-bit, prefetchable) [size=128M]
	Region 3: Memory at 381fd0000000 (64-bit, prefetchable) [size=32M]
	Region 5: I/O ports at c000 [size=128]
	[virtual] Expansion ROM at f5000000 [disabled] [size=512K]
```
my K2 host BARs:
```
06:00.0 3D controller: NVIDIA Corporation GK104GL [GRID K2] (rev a1)
	Subsystem: NVIDIA Corporation Device 1045
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 177
	Region 0: Memory at c5000000 (32-bit, non-prefetchable) [size=16M]
	Region 1: Memory at 2ffd8000000 (64-bit, prefetchable) [size=128M]
	Region 3: Memory at 2ffe0000000 (64-bit, prefetchable) [size=32M]
	[virtual] Expansion ROM at c6000000 [disabled] [size=512K]
```

my K260 guest BARs in windows:
```
```

**Comment by kharbranth** [comment]
Thank you for the suggestions (I have yet to test `fb_bar1_strap_mb`, but I will soon).

First, I was testing to make sure that my Xen setup was working properly at all and it is (verified Pascal success on Xen 😀). Thus this is narrowed down to be a Kepler problem and not some other issue with the setup (I am certain this will also work with xcp-ng with even less modifications than originally described in this repository)

Probably has nothing to do with it—but... I may also note that running _any_ **Linux HVM domU** on this Kepler host is **completely** broken (CPU soft-lockup—similar to [this](https://serverfault.com/questions/94789/soft-lockup-cpu0-stuck-for-11s-error-with-xen-virtual-machines) very outdated post), but Linux domU works 100% fine in my Pascal test system (two different desktops, Kepler test system is running garbage AMD FX8370 CPU from 2016 and the other one is running a newer Ryzen 3). Actually, there is a bug where Linux will hang at `Booting SMP configuration` and vCPUs has to be set to **1** or Linux will indefinitely hang on this FX system. Once vCPUs is set, it will take 1 hour or so to get to a shell, and then the system will be unusable (soft lockup). 

**Kepler dom0 `lspci -vvv`**:

```
01:00.0 VGA compatible controller: NVIDIA Corporation GK110 [GeForce GTX 780] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: eVga.com. Corp. GK110B [GeForce GTX 780 SC w/ ACX Cooler]
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 24
	NUMA node: 0
	Region 0: Memory at fd000000 (32-bit, non-prefetchable) [size=16M]
	Region 1: Memory at f0000000 (64-bit, prefetchable) [size=128M]
	Region 3: Memory at f8000000 (64-bit, prefetchable) [size=32M]
	Region 5: I/O ports at e000 [size=128]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
```

**domU Windows BAR mappings (does not say K260Q because NVIDIA driver not loaded)**:

![image](https://user-images.githubusercontent.com/72760020/117558826-731ab580-b04e-11eb-9882-cccb06413a55.png)


Here is the output of `/var/log/messages`, filtered for only vGPU logs: [SYSLOG-logs.txt](https://github.com/kharbranth/vGPU-unlock-Kepler-xcp-ng/files/6446863/SYSLOG-logs.txt) (**this log contains extremely verbose logging because of a modification I made to `vgpu_unlock` to print out `op_type` of every `ioctl()` that occurs**)

Logs for `/var/log/xen/*win1_manual.log`: [varlog-xenlogs.txt](https://github.com/kharbranth/vGPU-unlock-Kepler-xcp-ng/files/6446867/varlog-xenlogs.txt)


>  Can you check K110 in host ?

I am not sure what you mean… there is no GRID K110 guest configuration or host card that I can spoof. Also, I did try a GRID K1 spoof at some point and I do not think it was successful, but I may test later on.

**Comment by Toby4213** [comment]
@kharbranth Does vGPU unlock work on XCP-ng? I already searched diligently but could find anything online except this repo. 
**Is there a forum/discord server I can join where this is discussed?** 
I have a couple of GPUs laying around and could test on an up to date XCP-ng host. You can contact my via twitter, see my github profile.

**Comment by kharbranth** [comment]
@Toby4213 Sorry for the extremely late response. I did this a loooong time ago, but it should work, but it's **extremely** hacky and has garbage integration with the system (use Xen on Fedora instead with mcerveny's work from this issue). The whole idea of this was to see if *Kepler* GPUs could be hacked into working on Xen since the newer generations worked on KVM, which is less painful to set up. 

It should work on the latest xcp-ng, but again, no integration. You basically have to start the virtual machines manually and nothing will work with GUI thing (xcp-ng center). You might as well try KVM. You could patch the xenops stuff to change the PCI ids so it would detect your card and integrate with the GUI, though, but I don't have the time or motivation to do that right now. And even that might require extra work

Don't recommend running this on Xen. Also Xen is a royal pain to set up. **But** if you're super interested though, it's 100% possible.

There's a Discord: https://discord.gg/5rQsSV3Byq
